name: convert
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    environment: proxy
    env:
      SO: ${{ vars.SO }}
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Hello
          run: echo "hello world"
        - name: Read a variable KOO
          run: echo "My APP_ID value is ${{ vars.KOO }}"
        - name: Read a variable SO
          run: echo "My APP_ID value is ${{ vars.SO }}"
        - name: Read a variable env SO
          run: echo "My APP_ID value is $SO"
        - name: Git Clone sing-box-subscribe
          run: |
            git clone https://github.com/Toperlock/sing-box-subscribe.git
            cd sing-box-subscribe
            pip install -r  requirements.txt --root-user-action=ignore
            
          

