name: convert
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    environment: proxy
    env:
      SO: ${{ vars.SO }}
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Git Clone sing-box-subscribe
          run: |
            git clone https://github.com/Toperlock/sing-box-subscribe.git
            cp providers.json sing-box-subscribe/
            cd sing-box-subscribe
            python3 -m pip install --upgrade pip --root-user-action=ignore
            pip install -r  requirements.txt --root-user-action=ignore
            python3 main.py --template_index=0
            
            
          

