name: convert
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Hello
          run: echo "hello world"
        - name: Hello Env
          run: echo " ${{ vars.PROXIES }} "
        - name: Hello KO
          run: echo echo " ${{ vars.KO }} "

