name: convert
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Hello
          run: echo "hello world"
        - name: Env HELLO
          run: echo ${{ vars.HELLO }}
        - name: repo Env KO
          run: echo " ${{ env.hello.KO }} "

