name: convert
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      PROXIES: ${{ vars.PROXIES }}
      CLOUDFLARE_EMAIL: ${{ vars.CLOUDFLARE_EMAIL }}
      CF_ACCOUNT_ID: ${{ vars.CF_ACCOUNT_ID }}
      KV_NAMESPACE_ID: ${{ vars.KV_NAMESPACE_ID }}
      CLOUDFLARE_API_KEY: ${{ vars.CLOUDFLARE_API_KEY }}
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: echo $PROXIES
          run: echo $PROXIES
        - name: Git Clone sing-box-subscribe
          run: |
            echo "Clone sing-box-subscribe repo"
            python3 --version
            git clone https://github.com/Toperlock/sing-box-subscribe.git
            echo "Generate providers.json"
            python3 providers.py
            echo "replace providers.json and template"
            mv providers.json sing-box-subscribe/
            mv config_template_groups_rule_set_tun.json sing-box-subscribe/config_template/
            echo "Generate subscribes"
            cd sing-box-subscribe
            python3 -m pip install --upgrade pip -q
            pip install -r  requirements.txt -q
            echo $PROXIES
            python3 main.py --template_index=0
            echo "Upload subscribe"
            mv config.json .. && cd ..
            pip install requests
            python3 upload.py

            
            
          

