name: convert
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Hello
          run: echo "hello world"
        - name: Read a variable KOO
          run: echo "My APP_ID value is ${{ vars.KOO }}"
        - name: Read a variable SO
          run: echo "My APP_ID value is ${{ vars.SO }}"

