name: convert
on:
  workflow_dispatch:
    inputs:
      profile:
        description: "Set the firmware size (in MB). "
        required: true
        default: '512'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Validate PPPoE Inputs
          run: |
            echo "hello world"

