name: Update

# on:
#   schedule:
#     - cron: '0 0 * * *'  # 每天午夜12点执行（UTC）

on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  update-template:
    runs-on: ubuntu-latest
    env:
      TEMPLATE_DOWNLOAD_URL: https://raw.githubusercontent.com/Toperlock/sing-box-subscribe/refs/heads/main/config_template/config_template_groups_rule_set_tun.json
      OLD_TEMPLATE: update/template/config_template_groups_rule_set_tun.json  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download current template
        run: |
          cd update/template
          wget $TEMPLATE_DOWNLOAD_URL -O new.json
      - name: Compare the templates
        run: |
          diff $OLD_TEMPLATE update/template/new.json
        id: diff_check
        continue-on-error: true
      - name: create an issue
        if: steps.diff_check.outcome == 'failure'
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Update providers.json
          body: Update providers.json
jobs:
  update-proxies:
    runs-on: ubuntu-latest
    env:
      PROXIES: ${{ vars.PROXIES }}
      CLOUDFLARE_EMAIL: ${{ vars.CLOUDFLARE_EMAIL }}
      CF_ACCOUNT_ID: ${{ vars.CF_ACCOUNT_ID }}
      KV_NAMESPACE_ID: ${{ vars.KV_NAMESPACE_ID }}
      CLOUDFLARE_API_KEY: ${{ vars.CLOUDFLARE_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compare the proxies
        run: |
          python3 -m pip install --upgrade pip -q
          pip install requests
          pip install cloudflare
          python3 download.py
          python3 diff.py
        id: diff_check
        continue-on-error: true
      - name: create an issue
        if: steps.diff_check.outcome == 'failure'
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Update proxies
          body: Update proxies
        
          
